# Generated by Django 2.2.6 on 2019-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geneDiseaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=300)),
                ('lenght', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kitOutputCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.CharField(max_length=30)),
                ('output', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tat', models.IntegerField(default=3)),
                ('batchsize', models.IntegerField(default=8)),
                ('dnaExtractionCost', models.FloatField(default=100)),
                ('libPrepCost', models.FloatField(default=300)),
                ('hybridKitCost', models.FloatField(default=200)),
            ],
        ),
    ]
