# Generated by Django 2.2.6 on 2019-10-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genediseaselist',
            old_name='lenght',
            new_name='length',
        ),
    ]
