# Generated by Django 2.2.6 on 2019-10-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0002_auto_20191012_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genediseaselist',
            options={'verbose_name_plural': 'Gene-Disease and length'},
        ),
        migrations.AlterModelOptions(
            name='kitoutputcost',
            options={'verbose_name_plural': 'Kit type, capacity & cost'},
        ),
        migrations.AlterModelOptions(
            name='variables',
            options={'verbose_name_plural': 'Basic Variables'},
        ),
        migrations.RemoveField(
            model_name='genediseaselist',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='genediseaselist',
            name='gene',
        ),
        migrations.AddField(
            model_name='genediseaselist',
            name='geneDisease',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='genediseaselist',
            name='length',
            field=models.IntegerField(default=100),
        ),
    ]
