# Generated by Django 2.2.6 on 2019-11-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0004_auto_20191103_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genediseaselist',
            options={'verbose_name_plural': 'GeneID and Disease'},
        ),
        migrations.AlterModelOptions(
            name='genelengthlist',
            options={'verbose_name_plural': 'Gene and length'},
        ),
    ]
