# Generated by Django 2.2.6 on 2019-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0005_auto_20191103_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='genediseaselist',
            name='genes',
            field=models.CharField(default='SOMEGENES', max_length=50000),
        ),
    ]
