# Generated by Django 2.2.6 on 2019-11-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0006_genediseaselist_genes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelengthlist',
            name='geneID',
        ),
    ]
