# Generated by Django 2.2.6 on 2019-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0008_auto_20191115_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='hybridizationRxnCount',
            field=models.IntegerField(default=3),
        ),
    ]
