# Generated by Django 2.2.6 on 2019-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtapp', '0009_variables_hybridizationrxncount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='hybridizationRxnCount',
            field=models.IntegerField(default=2),
        ),
    ]
